CREATE DATABASE pizza;

USE pizza;

CREATE TABLE TB_PIZZA(
ID_PIZZA          INT PRIMARY KEY AUTO_INCREMENT,
NM_PIZZA          VARCHAR(200),
VL_PRECO          DECIMAL(15,2),
QTD_QUANTIDADE    INT,
DS_INGREDIENTES   VARCHAR(100),
DS_FOTO           VARCHAR(100)  
);