CREATE DATABASE pizza;

USE pizza;

CREATE TABLE TB_PIZZA(
ID_PIZZA          INT PRIMARY KEY AUTO_INCREMENT,
NM_PIZZA          VARCHAR(200),
VL_PRECO          DECIMAL(15,2),
QTD_QUANTIDADE    INT,
DS_INGREDIENTES   VARCHAR(100),
DS_FOTO           VARCHAR(100)  
);

INSERT INTO TB_PIZZA (NM_PIZZA, VL_PRECO, QTD_QUANTIDADE, DS_INGREDIENTES, DS_FOTO)
			   VALUES(?, ?, ?, ?, ?);

SELECT ID_PIZZA AS ID,
       NM_PIZZA  AS NOME,
       VL_PRECO  AS PREÇO,
       QTD_QUANTIDADE AS QUANTIDADE,
       DS_INGREDIENTES AS INGREDIENTES,
       DS_FOTO AS FOTO
       FROM TB_PIZZA;